apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: 'course-discovery'
  links:
    - url: "http://github.com/openedx/course-discovery"
      title: "Source Code"
      icon: "Code"
relations:
  - target:
      kind: resource
      namespace: default
      name: edx-platform
    type: dependsOn
spec:
  owner: group:engage
  type: 'backend-service'
